### ISSUE TITLE
Use BBA with PicoBoot?

### ISSUE THREAD

**Issue by super56kgames** [webhdx/PicoBoot#10]
First off, THANK YOU for all of your hard work on this project. :) 

My question is, since some of these connections are to the backside of the serial-port that the Broad Band Adapter uses, can I still use said adapter after PicoBoot is installed?

I have two GameCubes and BOTH have a Broad Band Adapter and a GameBoy Player attached. Thanks!

**Comment by marl64** [comment]
i've yet to try this mod myself, but i believe since the pico only is active during boot, it shouldn't affect any operation of the BBA afterwards

**Comment by webhdx** [comment]
This is correct. You can use BBA with Pico boot.

**Comment by super56kgames** [comment]
Thank you. I'll be inatalling after the pis arrive.
