### ISSUE TITLE
Controllers ports 1-3 not working after picoboot installed 

### ISSUE THREAD

**Issue by fugi95** [webhdx/PicoBoot#103]
| Answer some general questions first                             	  |  	     |
|:-------------------------------------------------------------------	|:------:|
| Which firmware version are you using?                             	| `v0.2` |
| Are you using the official Raspberry Pi Pico board?                  yes

Hi, I have lots of experience soldering so I don’t believe that’s the issue. I made sure my wires were 4 inches long and soldered everything nicely. Also put a piece of tape over the wires under the heat sync to avoid a short. 

Issue I’m having is swish boots up and ports 1-3 on the GameCube do not work at all. Port four works but once I choose a game I can actually start the game once I’m in it because I’m controller 4. 

Any advice ?

**Comment by webhdx** [comment]
Not related to PicoBoot. You either have failing capacitors and strange things are happening or you should reseat controller panel flex cable. It could've been damaged too.
