### ISSUE TITLE
Serial Port Issue

### ISSUE THREAD

**Issue by BarryBlueJeans69** [webhdx/PicoBoot#12]
I have DOL-101 in my GameCube and after soldering in the Pico, reassembling it, and installing Swiss and my favorite games onto an SD card.... There is no port to put the SD2SP2. Under the cover for serial port 2 there is only plastic. Will this mod still work without that particular adapter, would a SD Gecko or any other SD to Memory Card adapter work instead?

**Comment by webhdx** [comment]
https://github.com/webhdx/PicoBoot#prerequisites

You can use SD Gecko. Please read the instruction in the main page of this repository.
