### ISSUE TITLE
SD card partition layout table: msdos vs GPT

### ISSUE THREAD

**Issue by RincewindLangner** [webhdx/PicoBoot#19]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.1` 	|
| Did you compile it yourself?                             	| no 	|
| Do you use alternative install method not mentioned in the guide? 	| no 	|
| Are you using official Raspberry Pi Pico board?                   	| yes |
| Did you pay someone to install it for you?                        	| no 	|

using a :
* Pico 2020 version
* SD2SP2 1.a board

The game cube would boot straight to the original bios aka the stock loading screen. Checked all wiring etc, all correct. The problem was solved by checking what type of partition table the sd card was using. The card, while formatted to exFAT/vFAT was was using GPT partition and wouldn't read. Once the partition table was changed to msdos all was well and it read fine. 

Thanks for the mod.

**Comment by webhdx** [comment]
I recommend sticking to FAT32 - exFAT is only supported in Swiss and iplboot for now. It also doesn't work with IGR feature. Thanks for the feedback!
