### ISSUE TITLE
DVD Disc init on SWISS after Boot 

### ISSUE THREAD

**Issue by flo0306** [webhdx/PicoBoot#20]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	| 
| Did you check older issues to see if it was requested before? | yes 	|

Hello, 
I succeeded to install my Picoboot and I have noticed different behaviour if I boot Swiss with ipl.dol or by pressing a specific button on the controller. For example, I prefer to keep the original gamecube boot if no button are pressed (for that I do not place any ipl.dol file in the SD card and I renamed the swiss file B.dol). In this case, Swiss is booting only if I press B on the controller but for an unknown reason the DVD drive is not initialized compared to the boot with ipl.dol. If I use a DVD game it is not recognized.
Are the boot in ipl.dol and any other boot with controller button managed differently ?
Thank you for your answer and the amazing job you did !

**Comment by webhdx** [comment]
B button is also used by Swiss to skip disc drive initialization. What happens is most likely you hold B for too long and Swiss understands that as disc drive skip. Try assigning Swiss to either X or Y button.

**Comment by flo0306** [comment]
It worked ! Thanks !
