### ISSUE TITLE
Just an install question

### ISSUE THREAD

**Issue by rayrayrayraydog** [webhdx/PicoBoot#25]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	|
| Did you check older issues to see if it was requested before? | yes 	|

Do I *need* to reinstall the optical drive with Picoboot for any reason?  Mine is broken and I would rather leave it out.

**Comment by webhdx** [comment]
Vanilla IPL will display error message if there is no drive installed. Swiss can work without the disc drive. If you don't plan to use standard GC menu then you should be fine with no disc drive.

**Comment by rayrayrayraydog** [comment]
I'm new to 'cube modding.  I assume Swiss is all I need.  Thanks for clarifying.  Leaving out the optical drive should also keep the Pico more easily accessible for updates.

**Comment by Extrems** [comment]
I recommend leaving it in.

**Comment by rayrayrayraydog** [comment]
What are the advantages of leaving it in then, if it doesn't work?

**Comment by Extrems** [comment]
You can expect a lot of software to hang for at least 10 seconds if there's no disc drive present.

**Comment by rayrayrayraydog** [comment]
I see.  I guess I'll try it both ways and see what happens.  Thanks.
