### ISSUE TITLE
Select Boot Image

### ISSUE THREAD

**Issue by maniaco007** [webhdx/PicoBoot#27]
It would be possible to create a way to customize the boot screen, just like this user did: https://youtu.be/sCODnY4vml4 .

Unfortunately he did not explain how to proceed.

**Comment by kjuno** [comment]
This approach requires modifying and recompiling iplboot, see https://github.com/redolution/iplboot for compiling for PicoBoot

**Comment by webhdx** [comment]
Yes you need to compile your own version of iplboot (or whatever you want). We are working on getting patched IPL to run from PicoBoot, this will bring back cube animation before Swiss loads.

**Comment by kjuno** [comment]
wouldnt be possible to use a video file loaded from sd for the startup sequence?

**Comment by webhdx** [comment]
Anything is possible but you have to code it yourself. Iplboot is meant to be minimal and it's unlikely anything like this will be added to it anytime soon. If there is interest in it maybe you should fork iplboot and try adding it yourself.
