### ISSUE TITLE
Can you provide changelog or github for iplboot r7?

### ISSUE THREAD

**Issue by Ch0z** [webhdx/PicoBoot#3]
Hi,

Sorry to bother, can you provide a changelog or github for iplboot r7?

I can't find it.

By the way big thanks for your work on Picoboot.

**Comment by webhdx** [comment]
Source code is here: https://github.com/seewood/iplboot 

The only change added in r7 is support for multiple `*.dol` files:
- `x.dol` - hold X during boot
- `y.dol` - hold Y during boot
- `b.dol` - hold B during boot
- `ipl.dol` - loaded by default

There is also a nice side effect that let's you boot standard GameCube IPL by holding any of X/Y/B buttons if there is no designated file present on an SD card.
