### ISSUE TITLE
Wiki URL incorrect

### ISSUE THREAD

**Issue by Woovie** [webhdx/PicoBoot#35]
### Problem

https://github.com/webhdx/PicoBoot/wiki/FAQ

See the `license agreements` URL. When clicking, it redirects as the page doesn't exist.

![image](https://user-images.githubusercontent.com/7304619/186518364-202a67e7-5a7b-4865-a807-f5a7c88cf2c8.png)

![image](https://user-images.githubusercontent.com/7304619/186518401-4374a4ea-8553-4bff-ab0b-3428c8512efa.png)

**Comment by webhdx** [comment]
Thanks @Woovie for the report. I've fixed it.
