### ISSUE TITLE
Splash screens

### ISSUE THREAD

**Issue by Zonark** [webhdx/PicoBoot#38]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	|
| Did you check older issues to see if it was requested before? | yes 

wanted to see if this is a possibility? I know it will have to be rather small but maybe having the ability to add one to cover the coding at the beginning.

**Comment by bart1ebee** [comment]
See [#27](https://github.com/webhdx/PicoBoot/issues/27)
