### ISSUE TITLE
Feature list missing in Wiki

### ISSUE THREAD

**Issue by mauricewoelk** [webhdx/PicoBoot#39]
| Are you my GitHub sponsor? | no	|
| Did you check older issues to see if it was requested before? | yes |

The feature-list is missing in the Wiki of this repo. 
It would be nice to see all features of PicoBoot here and not only in some forums like reddit or in YT videos.

**Comment by webhdx** [comment]
For feature list please refer to https://github.com/redolution/iplboot

PicoBoot comes preloaded with iplboot. I'll try to make it more apparent in the description so people can go to iplboot and check all the features it offers.
