### ISSUE TITLE
process_ipl.py : outputs Invalid entry point?

### ISSUE THREAD

**Issue by A-Ibrahim** [webhdx/PicoBoot#4]
Trying to compile PicoBoot from source code, I'm I doing something incorrectly?   
PicoBoot (main)~ ./process_ipl.py swiss_r1336.dol ipl.h
Usage: ./process_ipl.py <executable> <output>
Entry point:   0x80003100
Load address:  0x00003100
Image size:    1839040 bytes (1795K)
Invalid entry point and base address (must be 0x81300000)

**Comment by webhdx** [comment]
Swiss is incompatible for now. Also it won't fit into the flash, the payload is 4x bigger after processing.

**Comment by webhdx** [comment]
PicoBoot injects small bootloader called [iplboot](https://github.com/redolution/iplboot) which is responsible for loading `ipl.dol` file.
