### ISSUE TITLE
Full IPL/BIOS Chip with Pico 

### ISSUE THREAD

**Issue by ramon-code** [webhdx/PicoBoot#40]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | No 	| 
| Did you check older issues to see if it was requested before? | Yes 	| 

First, thank you very much for developing this beautiful project.

Now the request, I bought a Gamecube and it doesn't give video, even the laser moves, I changed the Bios chip and it worked perfectly. The problem is that there are no replacements. So maybe the PICO can fully function as a BIOS replacement.

**Comment by webhdx** [comment]
It'll be very difficult to fully emulate RTC-DOL chip because it also includes RTC and SRAM. I want to eventually look into it but don't have high hopes for that.

**Comment by masplund91** [comment]
A further question to this topic, so the IPL IC is still needed for the mod to work? I've read on a reddit post that we're just by-passing it, I though we utilized the chip with the pico? The pins we connect to on the IPL chip are the CS and serial out?

**Comment by webhdx** [comment]
@masplund91 Yes you need a working DOL-RTC chip. PicoBoot only overrides IPL payload during initial bootup. DOL-RTC has more functionality to it - it handles RTC and SRAM too.
