### ISSUE TITLE
read from config file

### ISSUE THREAD

**Issue by kmagdziak** [webhdx/PicoBoot#43]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	|
| Did you check older issues to see if it was requested before? | yes 	|

Itd be cool if picoboot cound read from a config file where you could define which button is mapped to which iso/dol. that way in swiss you still have games with their title and not have to change the iso's name to a.dol, b.dol, etc

**Comment by webhdx** [comment]
This is not something PicoBoot is responsible for. What lets you boot different binaries is https://github.com/redolution/iplboot and support for ini configuration is already being worked on. I will release updated PicoBoot firmware as soon as there is new iplboot release.
