### ISSUE TITLE
Killed IPL Chip

### ISSUE THREAD

**Issue by EliteNinjaX** [webhdx/PicoBoot#49]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.1` 	|
| Did you compile it yourself?                             	| no 	|
| Do you use alternative install method not mentioned in the guide? 	| no 	|
| Are you using official Raspberry Pi Pico board?                   	| yes|
| Did you pay someone to install it for you?                        	| no 	|

I killed some of the pins on the IPL, and I don't know if I can save it or not. I was kind of thinking that maybe there is another pinout perhaps, or maybe get some advice about what to do from someone smarter then me.
![312159687_1512076705973304_6449793093401254106_n](https://user-images.githubusercontent.com/58321186/197435554-c87dd714-2eb9-4b33-88c1-5b750494ef9c.jpg)

**Comment by webhdx** [comment]
There is no way to fix it and no replacements are available because it's a proprietary chip. This board is a toast. Please mind the warning next time - the documentation clearly states to practice soldering before attempting to mod a GameCube.

**Comment by EliteNinjaX** [comment]
Yep that's my fault. I did practice some, but I was using a cheep Iron, and should have knew better.  I do have an extra board and will try again after I get a better Iron and practice even more. I won't give up with this project or even fixing this board just yet, thank you for your time and this project.
