### ISSUE TITLE
One wire NTSC Region switch

### ISSUE THREAD

**Issue by 666dsa666** [webhdx/PicoBoot#50]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	|
| Did you check older issues to see if it was requested before? | yes |

Would a at boot region switch for NTSC console be possible ?
https://www.gc-forever.com/wiki/index.php?title=Region_Switch
Using one wire and providing 3.3v or 0v would allow for US/JAP switch using a combination at boot.

**Comment by webhdx** [comment]
You don't really need to do region mod after installing PicoBoot. Swiss will let you play any region games, even using discs.
