### ISSUE TITLE
GC not booting

### ISSUE THREAD

**Issue by Marthswordmaster** [webhdx/PicoBoot#51]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.1` 	|v0.1
| Did you compile it yourself?                             	| yes/no 	|no
| Do you use alternative install method not mentioned in the guide? 	| yes/no 	|no
| Are you using official Raspberry Pi Pico board?                   	| yes/no 	|yes
| Did you pay someone to install it for you?                        	| yes/no 	|no

When turning on
![WhatsApp Image 2022-11-02 at 8 55 57 PM](https://user-images.githubusercontent.com/117329490/199639849-c058a55f-1770-4068-8bb7-5e9d3fc8fa5c.jpeg)
![WhatsApp Image 2022-11-02 at 8 55 56 PM (1)](https://user-images.githubusercontent.com/117329490/199639852-aaca5486-6166-4a45-b8d7-205882ab0a03.jpeg)
![WhatsApp Image 2022-11-02 at 8 55 56 PM](https://user-images.githubusercontent.com/117329490/199639853-84efca03-ebac-4e50-8ca2-019bf8f228ec.jpeg)
 the Gamecube it wont start but if I desolder GP4 form the ipl it starts and asks for calendar setup.

**Comment by bart1ebee** [comment]
It is hard to tell how long the wires are it is the most common problem they're too long.

**Comment by Marthswordmaster** [comment]
How long should they be?

> It is hard to tell how long the wires are it is the most common problem they're too long.

How long should they be?

**Comment by Marthswordmaster** [comment]
I measured them and they are like 28cm long

**Comment by renanbianchi** [comment]
![199639852-aaca5486-6166-4a45-b8d7-205882ab0a03](https://user-images.githubusercontent.com/57647129/199644143-ea9e99a0-d58c-4b71-a08c-95cb3c161f56.jpg)

Check if there is a short in this region.

**Comment by renanbianchi** [comment]
> I measured them and they are like 28cm long

There isn`t a specific number for wire lenght that i know of. Try to reduce the wiring to about 20cm or less.

**Comment by bart1ebee** [comment]
Here in the wiki 10cm or less https://github.com/webhdx/PicoBoot/wiki/Troubleshooting-tips#orange-light-is-on-but-it-doesnt-display-anything-on-the-screen

**Comment by Marthswordmaster** [comment]
> Here in the wiki 10cm or less https://github.com/webhdx/PicoBoot/wiki/Troubleshooting-tips#orange-light-is-on-but-it-doesnt-display-anything-on-the-screen

Thank you very much, I will change the length of the cables and see if it fixes it

**Comment by Marthswordmaster** [comment]
Hi I already changed the lenght and is now working, but I got no audio

**Comment by webhdx** [comment]
Audio has nothing to do with PicoBoot. If you are using GCVideo based HDMI adapter make sure "enhanced DVI" is enabled.

**Comment by Marthswordmaster** [comment]
> Audio has nothing to do with PicoBoot. If you are using GCVideo based HDMI adapter make sure "enhanced DVI" is enabled.

Im using the original av cable, it was working some minutes ago

**Comment by webhdx** [comment]
PicoBoot doesn't interfere with audio in any way. If you are absolutely sure it worked on your setup prior to PicoBoot installation, it's plausible you damaged something during the install.
