### ISSUE TITLE
Everything is working but I got no Audio now

### ISSUE THREAD

**Issue by Marthswordmaster** [webhdx/PicoBoot#52]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.1` 	|
| Did you compile it yourself?                             	| yes/no 	|
| Do you use alternative install method not mentioned in the guide? 	| yes/no 	|
| Are you using official Raspberry Pi Pico board?                   	| yes/no 	|
| Did you pay someone to install it for you?                        	| yes/no 	|

I make it work but now I got no audio at all.

**Comment by webhdx** [comment]
The issue was discussed in #51. Closing this one.
