### ISSUE TITLE
Pico seemingly ignored by console

### ISSUE THREAD

**Issue by aarmastah** [webhdx/PicoBoot#54]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.2` 	|
| Did you compile it yourself?                             	| no 	|
| Do you use alternative install method not mentioned in the guide? 	| no 	|
| Are you using official Raspberry Pi Pico board?                   	| no 	|
| Did you pay someone to install it for you?                        	| no 	|

I have an unofficial board that I have confirmed works in another GameCube console, trying to use the same model in this one is leading me nowhere. I tested continuity between my solder points and they all look good, yet the console only boots normally and will not display the debug output nor boot from SD. Anything I'm missing potentially?
![PXL_20221112_231025560](https://user-images.githubusercontent.com/1887380/201498390-cea3ee8b-4a54-4523-a0fe-82f9eb6617d5.jpg)
![PXL_20221112_231034222](https://user-images.githubusercontent.com/1887380/201498393-6a633494-c350-4ce4-b75b-66b463e05b16.jpg)

**Comment by webhdx** [comment]
1. Your wires are waaay too long.
2. As stated in FAQ you won't receive any support if using unofficial board.

**Comment by aarmastah** [comment]
> 1. Your wires are waaay too long.
> 2. As stated in FAQ you won't receive any support if using unofficial board.

1. Are they? I'll try shortening them to see if it helps.
2. That's totally fair lol. Just figured I would give it a shot anyway since this type of clone board worked in my other GC.

**Comment by webhdx** [comment]
I'm not even sure if all pins on that board match with the official one. With tens or hundreds of different RP2040 boards I can't support and test them all.

Check basic things first - is your Pico getting power?

**Comment by aarmastah** [comment]
> I'm not even sure if all pins on that board match with the official one. With tens or hundreds of different RP2040 boards I can't support and test them all.
> 
> Check basic things first - is your Pico getting power? 

The pico definitely gets power. When I turn the console on, it lights up red for PWR, same as when plugged in via USB.

I just shortened my wires and sadly am getting the same results.

![PXL_20221112_234938742.jpg](https://user-images.githubusercontent.com/1887380/201499091-1c562699-145d-414e-842a-ddf4d0856e38.jpg)

**Comment by webhdx** [comment]
I wouldn't use that board. My firmware is bootstrapped for particular flash chip. If this board uses a different one it'll have problems. I'm not even sure if it's pin compatible with the official Pico board. Just get the recommended one and you'll be good.

**Comment by aarmastah** [comment]
> I wouldn't use that board. My firmware is bootstrapped for particular flash chip. If this board uses a different one it'll have problems. I'm not even sure if it's pin compatible with the official Pico board. Just get the recommended one and you'll be good.

I purchased some official boards and it worked perfectly first try. Not sure why my first bootleg worked fine and the others didn't, but I'm just glad it ended up working out. Thanks!
