### ISSUE TITLE
Gamecube stopped working

### ISSUE THREAD

**Issue by KiritoDv** [webhdx/PicoBoot#64]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.1` 	|
| Did you compile it yourself?                             	| no 	|
| Do you use alternative install method not mentioned in the guide? 	| no 	|
| Are you using official Raspberry Pi Pico board?                   	| yes	|
| Did you pay someone to install it for you?                        	| no 	|

The gamecube worked without any issues until some crashes started happening, until a day i got an entire black screen with and without the picoboot installed
![IMG_2250](https://user-images.githubusercontent.com/36680385/201985418-e30e32fe-458b-499c-87c1-3c64983134da.jpg)
![IMG_2248](https://user-images.githubusercontent.com/36680385/201985440-90b77882-b1dc-403f-a4d5-aaf69288025d.jpg)

**Comment by webhdx** [comment]
You have possible short between pin 8 and 9 (top 2 pins on the left side on the picture)
