### ISSUE TITLE
Exception (DSI) occured

### ISSUE THREAD

**Issue by Abalduin-adm** [webhdx/PicoBoot#67]
Hey i am not sure what to do now really, i soldet it like in the instructions. but no it wont start.
![BOOT1](https://user-images.githubusercontent.com/110982992/202022260-2606be45-8392-4ac8-87a1-2032998de14c.jpeg)
![BOOT2](https://user-images.githubusercontent.com/110982992/202022269-930ecdc9-6610-42e8-b257-692455c0a2d5.jpeg)
![solder (1)](https://user-images.githubusercontent.com/110982992/202025321-2ac8387e-08b8-4216-bdb5-4a0bf56568bc.jpeg)
![solder (2)](https://user-images.githubusercontent.com/110982992/202025324-da4b7230-c641-4d76-86f7-ea8c971476a4.jpeg)

**Comment by Abalduin-adm** [comment]
maybe is a problem with swiss-gc, sorry if report to the wrong place

**Comment by webhdx** [comment]
PicoBoot is working because you see output from iplboot. Your problem most likely lays in SD card setup. Try another card, make sure it's FAT32 formatted.
