### ISSUE TITLE
Ability to boot stock bios

### ISSUE THREAD

**Issue by Adran-Marit** [webhdx/PicoBoot#8]
My understanding is that once the picoboot modchip is installed it will boot ipl.dol (most notably swiss), however I was wondering if there was a way to boot the stock bios with the chip installed without removing the SD2SP2?

Whether this is by not having the ipl.dol and just having b.dol for example to only boot swiss while holding B, and without the button press just boots the normal bios.

Many thanks and cool project, I hope it grows <3

**Comment by webhdx** [comment]
Yes. Don't put `ipl.dol` file at all and name Swiss as  one of `x/y/b.dol` files. Then you can load Swiss on demand.

> I just bought a SD gecko, for another 20 bucks out of my pocket, I hope it works with that...

It shouldn't cost you more than $5... Not sure where did you order it 🤔

**Comment by nex86** [comment]
> Owner

ordered it on Amazon with 2 day shipping from my country.
Anything cheaper would take weeks to months to ship..
