### ISSUE TITLE
I'm missing a port

### ISSUE THREAD

**Issue by rdistiso** [webhdx/PicoBoot#83]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Which firmware version are you using?                             	| `v0.2` 	| 
| Did you compile it yourself?                             	| No 	|No
| Do you use alternative install method not mentioned in the guide? 	| No 	|
| Are you using the official Raspberry Pi Pico board?                   	| Yes	|
| Did you pay someone to install it for you?                        	|No 	|

My GameCube is missing SP2 even though my model is DOL-001

**Comment by webhdx** [comment]
You can use SD Gecko adapter:

![image](https://user-images.githubusercontent.com/10212760/228233849-f1e10bb7-0c0e-47bb-b246-debbd799007e.png)

It works the same way as SD2SP2, the same performance and such.

**Comment by rdistiso** [comment]
Any recommendations for the size and brand? (That isn't SanDisk)

**Comment by webhdx** [comment]
I'm using various SD cards and never had any compatibility issues. I'd just get anything that is genuine, avoid buying knockoffs.

**Comment by rdistiso** [comment]
One last question, Can I patch my rom of Double Dash and use that because I want to play some mods on real hardware

**Comment by webhdx** [comment]
I haven't tested it myself. I'm not sure.

**Comment by rdistiso** [comment]
Thank you for your time
