### ISSUE TITLE
Discord invite URL expired

### ISSUE THREAD

**Issue by coolpick** [webhdx/PicoBoot#89]
![image](https://github.com/webhdx/PicoBoot/assets/1341176/56528554-cf80-4efe-8dc1-f53742de8748)
https://discord.gg/USmzJteq

Someone needs to update the readme's Discord invite URL (if the server is still up, that is)

**Comment by webhdx** [comment]
Sorry for late reply 😅 I've fixed the issue recently. Turns out only community servers can have indefinite invitation links. I had to change the configuration of the server to enable it. Thanks for the heads up.
