### ISSUE TITLE
a way to test picoboot without SD Gecko or SD2SP2

### ISSUE THREAD

**Issue by nex86** [webhdx/PicoBoot#9]
not an issue just a question..
Is it possible to test if the mod works when there is no sd card inserted?
Just want to make sure I soldered everything correctly. 
Right now the Gamecube acts normal like there is no mod installed at all.

Just a black screen with an "hello world" would be enough to make sure it actually works.
I don't have any idea how I would make this work.

**Comment by webhdx** [comment]
If it boots to normal IPL (cube animation) and green LED lights up then there is very high chance you did it correctly.

**Comment by kjuno** [comment]
wouldnt be a bad idea to have a hello world uf2 file, you can compile it yourself

**Comment by nex86** [comment]
> 

you'd have to compile that in power pc code since it needs to be executed on gamecube right?
I have no idea how to do this, but an idea would be just a dol file that is small enough to be included in the uf2 file.

**Comment by kjuno** [comment]
i already compiled one hello world dol with picoboot, isnt that hard.

**Comment by kjuno** [comment]
im sorry haha
