### ISSUE TITLE
No `return -1` if number of parameters is wrong

### ISSUE THREAD

**Issue by adriencarbonaro** [webhdx/PicoBoot#92]
Hi, thanks for this great repo !

I've noticed a bug when executing `process_ipl.py`.
The process does not `return -1` if the number of parameters is not ok. It ends up with this output : 
```
Usage: process_ipl.py <executable> <output>
Traceback (most recent call last):
  File "/home/***/picoboot/process_ipl.py", line 175, in <module>
    sys.exit(main())
  File "/home/***/picoboot/process_ipl.py", line 131, in main
    with open(sys.argv[1], "rb") as f:
IndexError: list index out of range
```

https://github.com/webhdx/PicoBoot/blob/9b5dea45532a959cbcbe1e3705e912b3ebc33eb8/process_ipl.py#L127

I think there should be a
```diff
     if len(sys.argv) != 4:
         print(f"Usage: {sys.argv[0]} <executable> <output>")
+        return -1
```

I've tested with the return, and it gives me this output (which I think is the wanted behaviour): 

```
Usage: process_ipl.py <executable> <output>
```

**Comment by webhdx** [comment]
Hello
Thanks for reporting this issue. I've fixed it in: https://github.com/webhdx/PicoBoot/commit/154739ca2097dd646c0d095970a00a9b8e336579

Best regards,
Maciej
