### ISSUE TITLE
GameCube always boots into normal boot up.

### ISSUE THREAD

**Issue by Link267** [webhdx/PicoBoot#93]
| Answer some general questions first                             	  |  	     |
|:-------------------------------------------------------------------	|:------:|
| Which firmware version are you using?                             	| v0.2 |
| Are you using the official Raspberry Pi Pico board?                 | yes |

Hello!

I am having trouble booting up into Swiss after the Picoboot install. The GameCube boots into its normal state every time no matter what I’ve tried.

Lights are on the pico board when the console is powered up however I’m not seeing troubleshoot info when holding down the D-Pad. I’m assuming this is due to my smartTV where I have a menu for “Channels” and the HDMIs that are connected but I miss out on the first few seconds of boot up because the tv has to load the input method (takes like 2-3 seconds).

My wires are all below 10cm and I believe the solder job went well even for my first time.

My files are in the correct locations and renamed (I went off the MachoNachoProductions video for install).

I replaced my SD2SP2 adapter with a GC2SD memory card but that didn’t work.

I read that GCHD-MKII also causes issues so I unplugged both the HDMI and the GCHD from the back of the GameCube but it still boots into the normal boot up.

As a test I removed everything to ensure the GameCube is still working fine and it’s perfectly reading disks and playing. After reinstallation it’s the same, reads disks and plays perfectly but never boots up Swiss.

At this point I’ve sunk so much time and money to get what should be an easy mod to even boot up properly. Not sure what the issue is here and I’m tired of tearing down this cube just to check.

![AE4544AD-C1F2-420D-AAF4-323DB42214F4](https://github.com/webhdx/PicoBoot/assets/138705245/6a80d3e4-2030-4ece-aded-10847b50e1a1)
![F50FB28D-460D-4DEB-A01B-E5E3F1DA4845](https://github.com/webhdx/PicoBoot/assets/138705245/7ddeb6a8-57fc-426a-b823-76b3be21c6e6)
![8A3F2CF5-17C4-43B4-8865-D892A4C10754](https://github.com/webhdx/PicoBoot/assets/138705245/f21eeda9-610d-4f24-990e-9cf4ac34a148)
![B0122F94-44F9-4CB7-9587-317DA0D2BC82](https://github.com/webhdx/PicoBoot/assets/138705245/de806bd6-7d3f-43d6-b168-543dc0bdaffc)

**Comment by webhdx** [comment]
Troubleshooting screen will last until you release D-Pad Down button. If you don't see it at all then there is something wrong with soldering. Judging by the photos, it looks all okay but maybe try resoldering both pins on IPL chip. Also try reheating ground wire because it requires much more heat to melt and make good connection.

**Comment by Link267** [comment]
Sounds good I’ll solder everything again then. Any recommendations on wire length? I’ve seen multiple answers to this but wasn’t sure what to actually use.

I’m using 26awg wire and the setup in the pics is about 9 and a half centimeters but that leaves literally no room for the pico board.

**Comment by webhdx** [comment]
10-12cm is recommended length. The shorter the wires are the better. 26 AWG is okay, I've used it for my installs too but you have to make sure there are no loose strands touching adjacent pins.

**Comment by Link267** [comment]
Here is the re-installation job on the motherboard. 

I twisted and tinned the wires beforehand and tried different angles to better see the contacts. 

Can you see anything that stands out before I attach to the pico board?

![92B753E8-44D0-4F91-9D0B-2292C2BAB4FE](https://github.com/webhdx/PicoBoot/assets/138705245/dcbe210d-eb02-475f-bda0-d170328b4868)
![B5D93E1F-0213-4989-AD2D-EE5615FC28C4](https://github.com/webhdx/PicoBoot/assets/138705245/4bf1e801-634e-4da0-a701-213f289b2ec0)
![22E9A0E9-2ACE-4D0D-B339-4C8E0B2C4DCA](https://github.com/webhdx/PicoBoot/assets/138705245/8be5332c-c149-48d3-9163-80f3a07dcb7d)

![8F1DA2E5-7A23-4A38-A0D2-B15F6C7F6862](https://github.com/webhdx/PicoBoot/assets/138705245/fc6992b0-ff75-46d9-8d15-bb3df1ef51e3)

**Comment by webhdx** [comment]
Everything looks good to my eyes. Just a word of caution - since the wires are quite thick and short you must be very careful to not pull on the cables because it's easy to rip legs from IPL chip.

**Comment by Link267** [comment]
It worked! Thank you so much for taking the time to look into this with me, going through threads for over a week I was about to give up. 

Much appreciated and awesome mod!

![C02F406E-DB0F-4743-A619-5E362636698A](https://github.com/webhdx/PicoBoot/assets/138705245/857ef3e6-128a-4b4b-9858-0fad0c67e93e)
