### ISSUE TITLE
PicoBoot doesn´t start with 32gb micro SD card

### ISSUE THREAD

**Issue by M4xmark** [webhdx/PicoBoot#95]
| Answer some general questions first                             	  |  	     |
|:-------------------------------------------------------------------	|:------:|
| Which firmware version are you using?                             	| `v0.2` |
| Are you using the official Raspberry Pi Pico board?                 | yes |
| Are you using SD2SP2 or SD Gecko?                                      | SD Gecko |

Hi, I started by installing a few Gamecubes. In all of them, I have used new micro SD cards from the brand Verbatim with a capacity of 16gb. Currently, I wanted to switch to a 32gb capacity, however, neither one works (also new ones from the Verbatim brand bought in the same store). I tried formatting the card to FAT32 and also to exFAT, but nothing worked, I always get the normal menu. PicoBoot always starts when I insert a micro SD card with a capacity of 16gb back.

Is there some limitation with SD Gecko reader? (I have DOL-101 without SP2)

**Comment by webhdx** [comment]
You should try with different SD card adapter. Cards should be formatted to FAT32 with MBR for highest compatibility.
